// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	RefreshToken string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ExpiresAt    time.Time
	RevokedAt    pgtype.Timestamptz
	IpAddress    *netip.Addr
	UserAgent    *string
}

type User struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	Name              *string
	Email             string
	EncryptedPassword []byte
	Activated         bool
	Provider          string
	Version           int32
}
