// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                uuid.UUID
	CreatedAt         pgtype.Timestamptz
	Name              *string
	Email             string
	EncryptedPassword []byte
	Activated         bool
	Provider          string
	Version           int32
}
