name: auth52
services:
  auth52:
    container_name: auth52
    build: .
    depends_on:
      - auth52_db
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./:/api

  auth52_db:
    image: postgres
    container_name: auth52_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: auth52
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth52_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth52 -d auth52_db"]
      interval: 5s
      timeout: 10s
      retries: 5
    
  migrate:
    container_name: auth52_migrations
    image: kukymbr/goose-docker
    volumes:
      - ./migrations:/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://auth52:password@auth52_db:5432/auth52_db?sslmode=disable
    depends_on:
      - auth52_db
  
volumes:
  pgdata: